{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-duration-extension.fullname" . }}
  labels:
    app: {{ template "job-duration-extension.name" . }}
    chart: {{ template "job-duration-extension.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "job-duration-extension.name" . }}
{{- end }}