replicaCount: 2

ingress:
  enabled: true
  path:
    - /fsm-extensions/job-duration-extension/
    - /fsm-extensions/job-duration-extension/(.*)
  hosts:
    - us.coresystems.net

internalingress:
  hosts:
    - ingress.us-1.coreinfra.io

env:
  NODEJS_ENV_START_CONFIG: "config/env-us.json"
  LOGSTASH_HOSTS: "sh1aelks.coresuite.com,sh2belks.coresuite.com"

istio:
  enabled: true
