apiVersion: v1
appVersion: "1.0"
description: "Job duration prediction extension"
name: job-duration-extension
fullname: job-duration-extension
businessComponent: CEC-SRV-FSM-EXT
businessCategory: non-critical
version: 1.0.0
