# Default values for backend-starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

maintainerTeam: "Jupyter"

image:
  frontend:
  repository: registry.dev.coresuite.com/job-duration-extension
  tag: auto-filled-by-pipeline
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 100Mi
    cpu: 150m
  requests:
    memory: 100Mi
    cpu: 100m

vault:
  enabled: true
  secrets:
    - name: prometheus
      path: monitoring/prometheus
      variables:
        - name: password
          bindTo: PROMETHEUS_PASSWORD
        - name: username
          bindTo: PROMETHEUS_USERNAME

service:
  type: ClusterIP
  port: 8080
  httpPort: 8080

annotations:
  prometheus.io/scrape-job: "kubernetes-common-pods"
  prometheus.io/path: "/portal/metrics"
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"

nodeSelector: {}

tolerations: []

affinity: {}

istio:
  enabled: false

internalingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
  path:
    - /fsm-extensions/job-duration-extension/
    - /fsm-extensions/job-duration-extension/(.*)
